### ISSUE TITLE
芝麻粒设置好友浇水、合种浇水，闪退

### ISSUE THREAD

**Issue by KANHUYIZHIGOU** [constanline/XQuickEnergy#235]
小米13安卓13miui14，magisk26.1+lsp1.8.6
芝麻粒v1.1.2闪退，升级芝麻粒v1.1.2-fix2闪退
下面是三方应用异常分析：
java.lang.NullPointerException: Attempt to read from field 'android.widget.CheckBox pansong291.xposed.quickenergy.ui.ListAdapter$ViewHolder.cb' on a null object reference in method 'void pansong291.xposed.quickenergy.ui.ListDialog$2.onClick(android.content.DialogInterface, int)'
	at pansong291.xposed.quickenergy.ui.ListDialog$2.onClick(ListDialog.java:211)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(

https://github.com/constanline/XQuickEnergy/assets/61071528/7f8a3f00-3081-4b82-b0dd-ccf88c619b45

ZygoteInit.java:954)

**Comment by WeyLee89** [comment]
新版已修复

**Comment by KANHUYIZHIGOU** [comment]
谢谢大佬
