### ISSUE TITLE
AntStall文件报错org.json.JSONException: No value for roadStatus

### ISSUE THREAD

**Issue by xx668888** [constanline/XQuickEnergy#284]
### 程序版本 / 框架版本 / 模块版本

1.1.6

### 系统版本 / Android版本

Android 10

### 详细描述问题发生的具体原因

2023-08-26 08:29:31  pansong291.xposed.quickenergy.hook.RpcUtil, response: {"gloryScore":411,"gloryScoreLimit":{},"memo":"SUCCESS","resultCode":"100","success":true,"toolList":[{"dataMap":{"accelerateSeconds":3600},"farmId":"10170815165601012088902357665223","gloryScoreLimit":0,"toolCount":17,"toolHoldLimit":20,"toolId":"501692887379063ACCELERATETOOL2088902357665223","toolInfo":[{"action":"SPORTS","buttonName":"运动会","color":"#e94040"}],"toolType":"ACCELERATETOOL","userId":"2088902357665223"},{"dataMap":{},"gloryScoreLimit":0,"toolCount":1,"toolHoldLimit":20,"toolId":"2088902357665223ANTIEP_OUTER_RIGHTS15960055152411","toolInfo":[{"action":"TOOLS","buttonName":"做任务","color":"#328eef"}],"toolType":"FENCETOOL","userId":"2088902357665223"},{"dataMap":{},"farmId":"","gloryScoreLimit":0,"toolCount":0,"toolHoldLimit":20,"toolInfo":[{"action":"TOOLS","buttonName":"做任务","color":"#328eef"}],"toolType":"NEWEGGTOOL","userId":"2088902357665223"},{"dataMap":{},"farmId":"","gloryScoreLimit":0,"toolCount":20,"toolHoldLimit":20,"toolId":"501583942408664SHARETOOL2088902357665223","toolInfo":[{"action":"SPORTS","buttonName":"运动会","color":"#e94040"}],"toolType":"SHARETOOL","userId":"2088902357665223"}]}
2023-08-26 08:29:31  pansong291.xposed.quickenergy.hook.RpcUtil, argument: com.alipay.antstall.village.roadmap, [{"source":"ch_appcenter__chsub_9patch","systemType":"android","version":"0.1.2308081346.4"}]
2023-08-26 08:29:31  pansong291.xposed.quickenergy.hook.RpcUtil, response: {"resultCode":"SUCCESS","resultDesc":"成功","roadList":[{"canUpdateMasterAlias":true,"donateCount":8,"donateLimit":1,"enterTime":1660721793000,"finishTime":1660721793000,"index":0,"leaveTime":1660721793000,"masterAlias":"农家乐","properties":{"unlockDesc":"故事的开端，你我永远美好的回忆。","villageDesc":"故事的开端，你我永远美好的回忆。原有的农家乐会留在豆豆村，有空回来看看哦～"},"status":"FINISH","userId":"2088902357665223","villageName":"豆豆村","villageType":"DD"},{"canUpdateMasterAlias":true,"donateCount":4,"donateLimit":4,"enterTime":1660721793000,"finishTime":1662419505000,"index":1,"leaveTime":1663682979000,"masterAlias":"海风冲浪店","properties":{"unlockDesc":"敬请期待","villageDesc":"这里有阳光、沙滩、海浪，以及热情的冲浪店。"},"status":"FINISH","userId":"2088902357665223","villageName":"海浪村","villageType":"HAILANG"},{"canUpdateMasterAlias":true,"donateCount":6,"donateLimit":6,"enterTime":1663682980000,"finishTime":1666912639000,"index":2,"leaveTime":1666912731000,"masterAlias":"我的花房","properties":{"unlockDesc":"完成海浪村的建设后可解锁","villageDesc":"这里四季如春，有一家让人心花怒放的花店。"},"status":"FINISH","userId":"2088902357665223","villageName":"鲜花村","villageType":"XIANHUA"},{"canUpdateMasterAlias":true,"donateCount":7,"donateLimit":7,"enterTime":1666912731000,"finishTime":1670394392000,"index":3,"leaveTime":1670394508000,"masterAlias":"火星体验馆","properties":{"unlockDesc":"完成鲜花村的建设后可解锁","villageDesc":"荒凉的大漠戈壁能满足你对火星的所有幻想。"},"status":"FINISH","userId":"2088902357665223","villageName":"戈壁村","villageType":"GEBI"},{"canUpdateMasterAlias":true,"donateCount":9,"donateLimit":9,"enterTime":1670394508000,"finishTime":1673088596000,"index":4,"leaveTime":1673088693000,"masterAlias":"温泉酒店","properties":{"unlockDesc":"完成戈壁村的建设后可解锁","villageDesc":"俺们村背靠大雪山，有天然温泉，竭诚为大家伙儿提供一站式滑雪度假服务。"},"status":"FINISH","userId":"2088902357665223","villageName":"雪山村","villageType":"XUESHAN"},{"canUpdateMasterAlias":true,"donateCount":12,"donateLimit":12,"enterTime":1673088693000,"finishTime":1679268368000,"index":5,"leaveTime":1679268376000,"masterAlias":"星空露营地","properties":{"unlockDesc":"完成雪山村的建设后可解锁","villageDesc":"在这里呼朋唤友，脚踏草原，仰望星空。"},"status":"FINISH","userId":"2088902357665223","villageName":"草原村","villageType":"CAOYUAN"},{"canUpdateMasterAlias":true,"donateCount":12,"donateLimit":12,"enterTime":1679268376000,"finishTime":1686872840000,"index":6,"leaveTime":1686872958000,"masterAlias":"小岛艺术馆","properties":{"unlockDesc":"完成草原村的建设后可解锁","villageDesc":"一束来自海岛的艺术之光。"},"status":"FINISH","userId":"2088902357665223","villageName":"小岛村","villageType":"XIAODAO"},{"canUpdateMasterAlias":true,"donateCount":0,"donateLimit":14,"enterTime":1686872958000,"index":7,"masterAlias":"洞穴民宿","properties":{"unlockDesc":"完成小岛村的建设后可解锁","villageDesc":"一场神奇的洞穴旅居体验，一起来睡个好觉吧。"},"status":"NEW","userId":"2088902357665223","villageName":"洞穴村","villageType":"YAODONG"},{"canUpdateMasterAlias":true,"donateCount":0,"donateLimit":14,"enterTime":1693009772237,"index":8,"masterAlias":"一间咖啡店","properties":{"unlockDesc":"完成洞穴村的建设后可解锁","villageDesc":"邂逅小桥流水、美味咖啡和一段美好时光。"},"status":"LOCK","userId":"2088902357665223","villageName":"古镇村","villageType":"GUZHEN"},{"canUpdateMasterAlias":true,"donateCount":0,"donateLimit":16,"enterTime":1693009772237,"index":9,"masterAlias":"音乐餐吧","properties":{"unlockDesc":"完成古镇村的建设后可解锁","villageDesc":"享受一段独具异域风情的梦幻之旅。"},"status":"LOCK","userId":"2088902357665223","villageName":"雨林村","villageType":"YULIN"},{"canUpdateMasterAlias":true,"donateCount":0,"donateLimit":16,"enterTime":1693009772237,"index":10,"masterAlias":"落日书屋","properties":{"unlockDesc":"完成雨林村的建设后可解锁","villageDesc":"记住山间的第一缕阳光和希望。"},"status":"LOCK","userId":"2088902357665223","villageName":"山谷村","villageType":"SHANGU"}],"success":true,"traceId":"2182a87016930097722282721e4b65","userInfo":{"currentCoin":{"amount":20964.18,"cent":2096418,"centFactor":100,"currency":"CNY","currencyCode":"CNY"},"currentVillageType":"YAODONG","donateCntByDonateCoin":58,"donateCoin":{"amount":870000.00,"cent":87000000,"centFactor":100,"currency":"CNY","currencyCode":"CNY"},"donateCount":58,"extJson":"{shiftTime=1660721793422, leadCategory=ALIVE, source=ANTFARM}","gmtRegister":1632920548000,"hot":0,"jobBuildLevelMap":{"jobBuildingA":3,"jobBuildingC":3},"level":9,"status":"FREE","totalCoin":{"amount":0.00,"cent":0,"centFactor":100,"currency":"CNY","currencyCode":"CNY"},"userId":"2088902357665223"},"viewVillage":"YAODONG"}
2023-08-26 08:29:31  pansong291.xposed.quickenergy.AntStall, roadmap err:
2023-08-26 08:29:31  pansong291.xposed.quickenergy.AntStall, org.json.JSONException: No value for roadStatus
	at org.json.JSONObject.get(JSONObject.java:403)
	at org.json.JSONObject.getString(JSONObject.java:564)
	at pansong291.xposed.quickenergy.AntStall.roadmap(AntStall.java:453)
	at pansong291.xposed.quickenergy.AntStall.home(AntStall.java:64)
	at pansong291.xposed.quickenergy.AntStall.access$000(AntStall.java:16)
	at pansong291.xposed.quickenergy.AntStall$1.run(AntStall.java:37)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

解决方案：
AntStall 文件 
line 452
先判断有没有再get可避免

if(road.has("roadStatus")){
                        if ("FINISHED".equals(road.getString("roadStatus"))) {
                            continue;
                        }
                        if ("LOCK".equals(road.getString("roadStatus"))) {
                            canNext = true;
                            break;
                        }
                    }

**Comment by constanline** [comment]
哦这里应该是
road.getString("status");
因为时间紧张出现了错漏，多谢提醒。今天更新
这里是不能用has("roadStatus")去判断的，不然没法确定状态，导致无法自动捐赠和更新小镇
