### ISSUE TITLE
同步步数失败

### ISSUE THREAD

**Issue by FunctionXJB** [constanline/XQuickEnergy#312]
### 程序版本 / 框架版本 / 模块版本

支付宝10.3.60.8100、LSPosed 1.8.6_mod(7020)、芝麻粒1.1.7

### 系统版本 / Android版本

MIUI14.0.5、Android 12

### 详细描述问题发生的具体原因

每天6点多同步步数失败，可能是后台问题，但是重启后没有再次同步。切换到水晶1.5.5修复版可立即成功同步步数

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

2023-08-30 06:21:56  pansong291.xposed.quickenergy.hook.RpcUtil, invoke err:
2023-08-30 06:21:56  pansong291.xposed.quickenergy.hook.RpcUtil, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcUtil.request(RpcUtil.java:75)
	at pansong291.xposed.quickenergy.hook.AntFarmRpcCall.queryFoodMaterialPack(AntFarmRpcCall.java:259)
	at pansong291.xposed.quickenergy.AntFarm.collectDailyLimitedFoodMaterial(AntFarm.java:1198)
	at pansong291.xposed.quickenergy.AntFarm.access$2000(AntFarm.java:15)
	at pansong291.xposed.quickenergy.AntFarm$1.run(AntFarm.java:237)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [7] : com.alipay.mobile.common.transport.ext.MMTPException: errorCode=[-1] errorMessage=[9]
	at com.alipay.mobile.common.rpc.transport.http.HttpCaller.httpException2RpcException(SourceFile:99)
	at com.alipay.mobile.common.rpc.transport.http.HttpCaller.call(SourceFile:1768)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(SourceFile:77)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(SourceFile:344)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(SourceFile:174)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy7.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(SourceFile:77)
	... 6 more

2023-08-30 06:21:56  pansong291.xposed.quickenergy.AntFarm, {"resultCode":"FAIL","memo":"MMTPException","resultDesc":"MMTPException"}
2023-08-30 06:21:56  pansong291.xposed.quickenergy.hook.RpcUtil, invoke err:
2023-08-30 06:21:56  pansong291.xposed.quickenergy.hook.RpcUtil, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcUtil.request(RpcUtil.java:75)
	at pansong291.xposed.quickenergy.hook.AntSportsRpcCall.userTaskGroupQuery(AntSportsRpcCall.java:108)
	at pansong291.xposed.quickenergy.AntSports.userTaskGroupQuery(AntSports.java:397)
	at pansong291.xposed.quickenergy.AntSports.access$400(AntSports.java:13)
	at pansong291.xposed.quickenergy.AntSports$1.run(AntSports.java:46)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [7] : com.alipay.mobile.common.transport.ext.MMTPException: errorCode=[-1] errorMessage=[9]
	at com.alipay.mobile.common.rpc.transport.http.HttpCaller.httpException2RpcException(SourceFile:99)
	at com.alipay.mobile.common.rpc.transport.http.HttpCaller.call(SourceFile:1768)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(SourceFile:77)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(SourceFile:344)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(SourceFile:174)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy7.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(SourceFile:77)
	... 6 more

2023-08-30 06:21:56  pansong291.xposed.quickenergy.util.Log, 同步运动步数失败:29927
2023-08-30 06:21:56  pansong291.xposed.quickenergy.hook.RpcUtil, invoke err:
2023-08-30 06:21:56  pansong291.xposed.quickenergy.AntSports, userTaskGroupQuery err:
2023-08-30 06:21:56  pansong291.xposed.quickenergy.hook.RpcUtil, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcUtil.request(RpcUtil.java:75)
	at pansong291.xposed.quickenergy.hook.AntForestRpcCall.queryEnergyRainHome(AntForestRpcCall.java:73)
	at pansong291.xposed.quickenergy.AntForest.energyRain(AntForest.java:1013)
	at pansong291.xposed.quickenergy.AntForest.access$400(AntForest.java:23)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:154)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [7] : com.alipay.mobile.common.transport.ext.MMTPException: errorCode=[-1] errorMessage=[9]
	at com.alipay.mobile.common.rpc.transport.http.HttpCaller.httpException2RpcException(SourceFile:99)
	at com.alipay.mobile.common.rpc.transport.http.HttpCaller.call(SourceFile:1768)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(SourceFile:77)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(SourceFile:344)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(SourceFile:174)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy7.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(SourceFile:77)
	... 6 more

2023-08-30 06:21:56  pansong291.xposed.quickenergy.AntSports, org.json.JSONException: No value for success
	at org.json.JSONObject.get(JSONObject.java:403)
	at org.json.JSONObject.getBoolean(JSONObject.java:424)
	at pansong291.xposed.quickenergy.AntSports.userTaskGroupQuery(AntSports.java:399)
	at pansong291.xposed.quickenergy.AntSports.access$400(AntSports.java:13)
	at pansong291.xposed.quickenergy.AntSports$1.run(AntSports.java:46)

</code></pre></details>

**Comment by TikTokJTT** [comment]
估计是掉后台了

**Comment by zhonghai9967** [comment]
我也是，116、117都不能自动增加步数了

**Comment by constanline** [comment]
看下新版效果如何

**Comment by FunctionXJB** [comment]
> 看下新版效果如何

谢谢已安装，这两天我再观察看看

**Comment by FunctionXJB** [comment]
应该是可以了，日志还是显示同步失败，但是支付宝运动里步数已经修改好了
