### ISSUE TITLE
森林日志无法正常显示，但是能正常采集。

### ISSUE THREAD

**Issue by cat-sir** [constanline/XQuickEnergy#356]
### 程序版本 / 框架版本 / 模块版本

1.2.0 LSPosed 1.9.1（6990）

### 系统版本 / Android版本

一加8Pro ColorOS13.1正式版，Android 13

### 详细描述问题发生的具体原因

![WechatIMG215](https://github.com/constanline/XQuickEnergy/assets/71893945/b3a3cf89-09bf-42bd-9f2d-97a891ff5e5b)
![WechatIMG216](https://github.com/constanline/XQuickEnergy/assets/71893945/8bca312c-862b-407a-8581-8471a4d6f4ad)
采集能量正常，其他日志也正常，唯独这个森林日志无法正常显示。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

2023-09-12 14:37:09  pansong291.xposed.quickenergy.util.FileUtils, java.io.FileNotFoundException: /storage/emulated/0/Download/xqe/forest.log: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileWriter.<init>(FileWriter.java:113)
	at pansong291.xposed.quickenergy.util.FileUtils.append2File(FileUtils.java:343)
	at pansong291.xposed.quickenergy.util.Log.forest(Log.java:25)
	at pansong291.xposed.quickenergy.AntForest.collectEnergy(AntForest.java:702)
	at pansong291.xposed.quickenergy.AntForest.collectEnergy(AntForest.java:647)
	at pansong291.xposed.quickenergy.AntForest.canCollectEnergy(AntForest.java:546)
	at pansong291.xposed.quickenergy.AntForest.checkCanCollectEnergy(AntForest.java:308)
	at pansong291.xposed.quickenergy.AntForest.queryEnergyRanking(AntForest.java:270)
	at pansong291.xposed.quickenergy.AntForest.access$100(AntForest.java:23)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:145)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8289)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more

</code></pre></details>

**Comment by constanline** [comment]
权限问题，尝试删掉这个文件，先开支付宝。 #282

**Comment by cat-sir** [comment]
> 权限问题，尝试删掉这个文件，先开支付宝。 #282

大佬，需要重装吗，我今天尝试了一下，操作如下：
到文件管理器删除/storage/emulated/0/Download/xqe/forest.log。
然后完全关闭芝麻粒呵支付宝，直接打开支付宝，但是现在情况还是一样的。
我应该按怎么样的顺序操作呢。麻烦指导一下，谢谢。

**Comment by constanline** [comment]
1、杀死芝麻粒进程
2、杀死支付宝进程
3、删除xqe文件夹下的forest.log文件
4、打开支付宝
5、查看forest.log是否创建，在创建之前不要打开芝麻粒

**Comment by constanline** [comment]
是否有效？

**Comment by Autines** [comment]
![Screenshot_20230920-074217_芝麻粒](https://github.com/constanline/XQuickEnergy/assets/16075324/6b540a91-0334-480e-afe3-2b6d083300ae)
我也是一样，只显示一条，然后乱码。
谷歌商店最新版本

**Comment by Hsf9812** [comment]
@constanline 已经按操作解决

> 1、杀死芝麻粒进程 2、杀死支付宝进程 3、删除xqe文件夹下的forest.log文件 4、打开支付宝 5、查看forest.log是否创建，在创建之前不要打开芝麻粒
