### ISSUE TITLE
v1.2.2 initHandler err

### ISSUE THREAD

**Issue by Fansirsqi** [constanline/XQuickEnergy#395]
### 程序版本 / 框架版本 / 模块版本

LSPosed:v1.9.1(6990) 

### 系统版本 / Android版本

miui13,android12

### 详细描述问题发生的具体原因

v1.2.2
未正常加载时的状态栏
![image](https://github.com/constanline/XQuickEnergy/assets/38542005/cc1cb7f0-dd9f-4d1b-aff1-2e9e56dda410)
退回V1.2.1后正常
![image](https://github.com/constanline/XQuickEnergy/assets/38542005/3c251de9-49a3-4f8c-af2e-61c7084018f5)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)
runtime.log
```log
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, hook login successfully
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, Service onCreate
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Log, 注册广播接收器成功com.alipay.dexaop.power.RuntimePowerService@ff2950f
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, get config fromcom.eg.android.AlipayGphone
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.FileUtils, [com.eg.android.AlipayGphone][config]读:true;写:true
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, limitCount:50
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, doubleCard:true
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:true
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.RpcUtil, get RpcCallMethod successfully
2023-10-10 18:24:07  pansong291.xposed.quickenergy.util.Log, 尝试初始化
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, initHandler err:
2023-10-10 18:24:07  pansong291.xposed.quickenergy.hook.XposedHook, java.lang.NullPointerException: Attempt to invoke virtual method 'long org.json.JSONObject.optLong(java.lang.String, long)' on a null object reference
        at pansong291.xposed.quickenergy.data.RuntimeInfo.getLong(RuntimeInfo.java:63)
        at pansong291.xposed.quickenergy.AntForestNotification.setContentText(AntForestNotification.java:116)
        at pansong291.xposed.quickenergy.AntForestNotification.start(AntForestNotification.java:41)
        at pansong291.xposed.quickenergy.hook.XposedHook.initHandler(XposedHook.java:134)
        at pansong291.xposed.quickenergy.hook.XposedHook.access$200(XposedHook.java:27)
        at pansong291.xposed.quickenergy.hook.XposedHook$4.afterHookedMethod(XposedHook.java:195)
        at vlhsWrOYnOPKxC.xz.j.nj.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
        at J.callback(Unknown Source:292)
        at LSPHooker_.onCreate(Unknown Source:8)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4607)
        at android.app.ActivityThread.access$1800(ActivityThread.java:264)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2121)
        at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:35)
        at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:49)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8105)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

</code></pre></details>

**Comment by JustinTangChina** [comment]
遇到同样问题

**Comment by Cgccvhgvhvv** [comment]
同样问题+1

**Comment by Potat0000** [comment]
请问 1.2.1 和 1.2.2 版本是在哪里下载的？Release 中只看到了 1.2.0。谢谢！

**Comment by Fansirsqi** [comment]
请fork作者仓库后自行编译



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 16, 2023 18:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [constanline/XQuickEnergy] v1.2.2 initHandler err (Issue #395)




 
请问 1.2.1 和 1.2.2 版本是在哪里下载的？Release 中只看到了 1.2.0。谢谢！

**Comment by dh53128** [comment]
> 请fork作者仓库后自行编译
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Oct 16, 2023 18:12 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [constanline/XQuickEnergy] v1.2.2 initHandler err (Issue #395) 请问 1.2.1 和 1.2.2 版本是在哪里下载的？Release 中只看到了 1.2.0。谢谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

麻烦问一下你用的什么打包的。我用的[Wsine/android_builder](https://github.com/Wsine/android_builder)始终报错

**Comment by constanline** [comment]
未发现问题，使用新版试试看
