### ISSUE TITLE
挂后台1h之后就报错“[2000] : 登录超时，请重新登录”

### ISSUE THREAD

**Issue by Ngwind** [constanline/XQuickEnergy#40]
启动后能成功收能量，但是1h之后，就出现报错。然后下一次定时检测时间，继续报一样的错。
请问各位大佬有遇到过吗？

日志如下：
```log
2023-07-27 17:00:07  pansong291.xposed.quickenergy.util.Log, 定时检测开始
2023-07-27 17:00:08  pansong291.xposed.quickenergy.hook.RpcUtil, invoke err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.hook.RpcUtil, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcUtil.requestRpc(RpcUtil.java:66)
	at pansong291.xposed.quickenergy.hook.RpcUtil.request(RpcUtil.java:53)
	at pansong291.xposed.quickenergy.hook.AntForestRpcCall.queryHomePage(AntForestRpcCall.java:22)
	at pansong291.xposed.quickenergy.AntForest.canCollectSelfEnergy(AntForest.java:262)
	at pansong291.xposed.quickenergy.AntForest.access$000(AntForest.java:19)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:112)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [2000] : 登录超时，请重新登录
	at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(SourceFile:66)
	at com.alipay.mobile.common.rpc.protocol.json.JsonDeserializerV2.parser(SourceFile:24)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(SourceFile:7)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(SourceFile:362)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(SourceFile:174)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy6.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(SourceFile:74)
	... 7 more

2023-07-27 17:00:08  pansong291.xposed.quickenergy.hook.RpcUtil, invoke err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.hook.RpcUtil, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcUtil.requestRpc(RpcUtil.java:66)
	at pansong291.xposed.quickenergy.hook.RpcUtil.request(RpcUtil.java:53)
	at pansong291.xposed.quickenergy.hook.AntFarmRpcCall.enterFarm(AntFarmRpcCall.java:7)
	at pansong291.xposed.quickenergy.AntFarm$1.run(AntFarm.java:74)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [2000] : 登录超时，请重新登录
	at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(SourceFile:66)
	at com.alipay.mobile.common.rpc.protocol.json.JsonDeserializerV2.parser(SourceFile:24)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(SourceFile:7)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(SourceFile:362)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(SourceFile:174)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy6.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(SourceFile:74)
	... 5 more

2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntFarm, AntFarm.start.run err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntFarm, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.AntFarm$1.run(AntFarm.java:79)

2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, canCollectSelfEnergy err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.AntForest.canCollectSelfEnergy(AntForest.java:270)
	at pansong291.xposed.quickenergy.AntForest.access$000(AntForest.java:19)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:112)

2023-07-27 17:00:08  pansong291.xposed.quickenergy.util.Log, 收【0克】，帮【0克】，0个蹲点任务
2023-07-27 17:00:08  pansong291.xposed.quickenergy.util.Log,   收：0，帮：0
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, queryEnergyRanking err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.AntForest.queryEnergyRanking(AntForest.java:198)
	at pansong291.xposed.quickenergy.AntForest.access$100(AntForest.java:19)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:113)

2023-07-27 17:00:08  pansong291.xposed.quickenergy.util.Log, 收【0克】，帮【0克】，0个蹲点任务
2023-07-27 17:00:08  pansong291.xposed.quickenergy.util.Log,   收：0，帮：0
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, popupTask err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.AntForest.popupTask(AntForest.java:156)
	at pansong291.xposed.quickenergy.AntForest.access$300(AntForest.java:19)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:116)

2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, energyRain err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.AntForest.energyRain(AntForest.java:685)
	at pansong291.xposed.quickenergy.AntForest.access$400(AntForest.java:19)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:118)

2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, waterFriendEnergy err:
2023-07-27 17:00:08  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.AntForest.waterFriendEnergy(AntForest.java:561)
	at pansong291.xposed.quickenergy.AntForest.access$600(AntForest.java:19)
	at pansong291.xposed.quickenergy.AntForest$1.run(AntForest.java:127)

```

**Comment by constanline** [comment]
这种就是之前说的支付宝1小时后台Auth失效的情况，目前常见的方法包括
1、水晶155保活优秀
2、商家提醒
3、尝试调整保活方式

**Comment by Ngwind** [comment]
> 这种就是之前说的支付宝1小时后台Auth失效的情况，目前常见的方法包括 1、水晶155保活优秀 2、商家提醒 3、尝试调整保活方式

感谢大佬回复~ 我研究下看看
