### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by forkWo** [constanline/XQuickEnergy#436]
### 程序版本 / 框架版本 / 模块版本

1.2.3_beta6

### 系统版本 / Android版本

a14

### 详细描述问题发生的具体原因

打开zfb无反应

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(2023-12-07 10:11:18  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2023-12-07 10:11:18  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2023-12-07 10:11:18  pansong291.xposed.quickenergy.hook.XposedHook, hook login successfully
2023-12-07 10:11:18  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2023-12-07 10:11:18  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2023-12-07 10:11:18  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2023-12-07 10:11:21  pansong291.xposed.quickenergy.util.Config, get config fromcom.eg.android.AlipayGphone
2023-12-07 10:11:21  pansong291.xposed.quickenergy.util.FileUtils, config.json文件不存在
2023-12-07 10:11:21  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:1493)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1331)
	at pansong291.xposed.quickenergy.util.Config.syncStepCount(Config.java:1233)
	at pansong291.xposed.quickenergy.util.Config.tmpStepCount(Config.java:1241)
	at pansong291.xposed.quickenergy.hook.XposedHook$6.afterHookedMethod(XposedHook.java:251)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.readDailyStep(Unknown Source:8)
	at com.alibaba.health.pedometer.core.PedometerSDK$3.onTrigger(SourceFile:97)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent.access$000(SourceFile:80)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent$1.__run_stub_private(Unknown Source:21)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent$1.__run_stub(Unknown Source:17)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:13)
	at com.alipay.mobile.framework.aop.TaskMonitorPerfInterceptor.intercept0(Unknown Source:56)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:24)
	at com.alipay.mobile.framework.aop.PointAroundPerfInterceptor.intercept0(Unknown Source:71)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:24)
	at com.alipay.dexaop.monitor.chain.interceptors.RunningObjectInterceptor.intercept0(Unknown Source:64)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:24)
	at com.alipay.dexaop.DexAOPEntrySettings.java_lang_Runnable_run_proxy(SourceFile:12)
	at com.alipay.dexaop.DexAOPEntry.java_lang_Runnable_run_proxy(Unknown Source:0)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent$1.run(Unknown Source:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.alibaba.health.pedometer.core.proxy.impl.WorkThreadFactory$SafeRunnable.__run_stub_private(SourceFile:20)
	at com.alibaba.health.pedometer.core.proxy.impl.WorkThreadFactory$SafeRunnable.run(Unknown Source:36)
	at java.lang.Thread.run(Thread.java:1012)

2023-12-07 10:11:21  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at pansong291.xposed.quickenergy.util.Config.config2Json(Config.java:2110)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:1992)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1331)
	at pansong291.xposed.quickenergy.util.Config.syncStepCount(Config.java:1233)
	at pansong291.xposed.quickenergy.util.Config.tmpStepCount(Config.java:1241)
	at pansong291.xposed.quickenergy.hook.XposedHook$6.afterHookedMethod(XposedHook.java:251)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.readDailyStep(Unknown Source:8)
	at com.alibaba.health.pedometer.core.PedometerSDK$3.onTrigger(SourceFile:97)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent.access$000(SourceFile:80)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent$1.__run_stub_private(Unknown Source:21)
	at com.alibaba.health.pedometer.core.trigger.TriggerPointAgent$1.__run_stub(Unknown Source:17)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:13)
	at com.alipay.mobile.framework.aop.TaskMonitorPerfInterceptor.intercept0(Unknown Source:56)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:24)
	at com.alipay.mobile.framework.aop.PointAroundPerfInterceptor.intercept0(Unknown Source:71)
	at com.alipay.dexaop.perf.RunnableRunChain.proceed0(SourceFile:24)
	at com.alipay.dexaop.monitor.chain.intercepto)

</code></pre></details>

**Comment by lee1ei** [comment]
当前版本会出现xqe目录授权失败，两个目录都放了最新版的配置文件依然如此，卸载换回旧版仍无法使用，提示没有这个功能（用户信息界面），，支付宝是不是做了什么调整？

**Comment by forkWo** [comment]
> 当前版本会出现xqe目录授权失败，两个目录都放了最新版的配置文件依然如此，卸载换回旧版仍无法使用，提示没有这个功能（用户信息界面），，支付宝是不是做了什么调整？

什么都没改动，就升级了一下支付宝。第一天正常第二天就没日志了

**Comment by Oz-Starlit** [comment]
本人退回zfb10.3的版本可以正常使用

**Comment by acooler15** [comment]
是否在Download目录下建立`useMedia`文件或目录？

**Comment by constanline** [comment]
#481
