### ISSUE TITLE
beta6和10.5.53不起作用

### ISSUE THREAD

**Issue by zweidyx** [constanline/XQuickEnergy#458]
### 程序版本 / 框架版本 / 模块版本

10.5.53，beta6

### 系统版本 / Android版本

hyper

### 详细描述问题发生的具体原因

11号之前还能用的，更新beta6后用不了了，学习了一下是目录的问题，download下新建了文件夹，Android/media下文件夹也有了配置，但是不起作用，log都是空的，也读不了好友，进入支付宝也没有任何提示，但是修改步数起效了，支付宝和芝麻粒该给的权限都给了，删除后重新安装也是一样，我甚至重新刷了一遍系统，重新搞了好几次，后来找了水晶安装，也没用，不知道哪里出问题了
![9501c41555981caaebf5ed8e57ad8f0](https://github.com/constanline/XQuickEnergy/assets/4342148/056182d4-c34b-4c67-8a20-0d0fcc9f2d61)
![b9eef8f04c21a584eece22da8783f3a](https://github.com/constanline/XQuickEnergy/assets/4342148/678a2f89-9bab-4782-9668-eb5c9c1de26d)
![c61f87a331f9ef23aa91957fbdba087](https://github.com/constanline/XQuickEnergy/assets/4342148/b1b11964-834c-4f12-9847-442709ee3820)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.FileUtils, config.json文件不存在
2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:1493)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1331)
	at pansong291.xposed.quickenergy.util.Config.languageSimplifiedChinese(Config.java:414)
	at pansong291.xposed.quickenergy.util.LanguageUtil.setLocale(LanguageUtil.java:12)
	at pansong291.xposed.quickenergy.ui.MainActivity.onCreate(MainActivity.java:86)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at pansong291.xposed.quickenergy.util.Config.config2Json(Config.java:2110)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:1992)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1331)
	at pansong291.xposed.quickenergy.util.Config.languageSimplifiedChinese(Config.java:414)
	at pansong291.xposed.quickenergy.util.LanguageUtil.setLocale(LanguageUtil.java:12)
	at pansong291.xposed.quickenergy.ui.MainActivity.onCreate(MainActivity.java:86)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.FileUtils, statisticsFile.json文件不存在
2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Statistics, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.util.Statistics.json2Statistics(Statistics.java:857)
	at pansong291.xposed.quickenergy.util.Statistics.getStatistics(Statistics.java:751)
	at pansong291.xposed.quickenergy.util.Statistics.getText(Statistics.java:208)
	at pansong291.xposed.quickenergy.ui.MainActivity.onResume(MainActivity.java:114)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1615)
	at android.app.Activity.performResume(Activity.java:9057)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5202)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5245)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Statistics, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at pansong291.xposed.quickenergy.util.Statistics.statistics2Json(Statistics.java:1149)
	at pansong291.xposed.quickenergy.util.Statistics.json2Statistics(Statistics.java:1112)
	at pansong291.xposed.quickenergy.util.Statistics.getStatistics(Statistics.java:751)
	at pansong291.xposed.quickenergy.util.Statistics.getText(Statistics.java:208)
	at pansong291.xposed.quickenergy.ui.MainActivity.onResume(MainActivity.java:114)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1615)
	at android.app.Activity.performResume(Activity.java:9057)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5202)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5245)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-01-16 20:30:37  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2024-01-16 20:30:55  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, get config fromapp
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 20:34:26  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
2024-01-16 20:34:57  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2024-01-16 20:34:57  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2024-01-16 20:34:57  pansong291.xposed.quickenergy.hook.XposedHook, hook login successfully
2024-01-16 20:34:57  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2024-01-16 20:34:57  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2024-01-16 20:34:57  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, get config fromcom.eg.android.AlipayGphone
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.FileUtils, [com.eg.android.AlipayGphone][config]读:true;写:true
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 20:34:59  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, get config fromapp
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 20:35:07  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.FileUtils, [null][config]读:true;写:true
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 20:38:54  pansong291.xposed.quickenergy.util.FileUtils, [app][statistics]读:true;写:true
2024-01-16 20:39:08  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2024-01-16 20:39:08  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2024-01-16 20:39:08  pansong291.xposed.quickenergy.hook.XposedHook, hook login successfully
2024-01-16 20:39:08  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2024-01-16 20:39:08  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2024-01-16 20:39:08  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, get config fromcom.eg.android.AlipayGphone
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.FileUtils, [com.eg.android.AlipayGphone][config]读:true;写:true
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 20:39:10  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 20:41:10  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 20:42:23  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 20:42:47  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 20:44:39  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 20:45:50  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 21:03:04  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2024-01-16 21:03:04  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2024-01-16 21:03:04  pansong291.xposed.quickenergy.hook.XposedHook, hook login successfully
2024-01-16 21:03:04  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2024-01-16 21:03:04  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2024-01-16 21:03:04  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, get config fromcom.eg.android.AlipayGphone
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.FileUtils, [com.eg.android.AlipayGphone][config]读:true;写:true
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 21:03:06  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 21:03:35  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 21:03:42  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.FileUtils, [null][config]读:true;写:true
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 21:04:29  pansong291.xposed.quickenergy.util.FileUtils, [app][statistics]读:true;写:true
2024-01-16 21:04:53  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 21:10:07  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2024-01-16 21:10:07  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2024-01-16 21:10:07  pansong291.xposed.quickenergy.hook.XposedHook, hook login successfully
2024-01-16 21:10:07  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2024-01-16 21:10:07  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2024-01-16 21:10:08  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, get config fromcom.eg.android.AlipayGphone
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.FileUtils, [com.eg.android.AlipayGphone][config]读:true;写:true
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 21:10:08  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.FileUtils, [null][config]读:true;写:true
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, limitCollect:false
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-16 21:10:18  pansong291.xposed.quickenergy.util.FileUtils, [app][statistics]读:true;写:true
2024-01-16 21:16:50  pansong291.xposed.quickenergy.hook.XposedHook, Activity onResume

**Comment by Liujishou** [comment]
装个低版本的支付宝试试10.5.36

**Comment by zweidyx** [comment]
> 装个低版本的支付宝试试 10.5.36

试过了好几个旧版本也没用，包括安装之前的1.22fix也没用了

**Comment by Zhangfanyu1222** [comment]
> > 装个低版本的支付宝试试 10.5.36
> 
> 试过了好几个旧版本也没用，包括安装之前的1.22fix也没用了

旧版的支付宝，不是旧版的芝麻粒呀

**Comment by acooler15** [comment]
配置是支付宝自己新建的吗？

**Comment by constanline** [comment]
目前测试最新版支付宝+最新版芝麻粒无问题。这种情况很可能是权限问题，尝试移除xqe文件夹重新配置，或者使用useMedia配置
