### ISSUE TITLE
若干无法写入

### ISSUE THREAD

**Issue by MJRweb** [constanline/XQuickEnergy#475]
### 程序版本 / 框架版本 / 模块版本

程序版本10.5.66.8000     框架版本 lsp1.9.2     模块版本v1.2.3-beta12    

### 系统版本 / Android版本

Android14

### 详细描述问题发生的具体原因

例1  /storage/emulated/0/Download/xqe/
runtime.log没有写入权限!

还有很多这样的无法写入，基本xqe文件夹都没法写入
个人理解：模块没有给所有文件访问权限？模块没接入系统？系统给所有文件访问权限没得该模块

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.FileUtils, config.json文件不存在
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:1529)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1364)
	at pansong291.xposed.quickenergy.util.Config.languageSimplifiedChinese(Config.java:420)
	at pansong291.xposed.quickenergy.util.LanguageUtil.setLocale(LanguageUtil.java:12)
	at pansong291.xposed.quickenergy.ui.SettingsActivity.onCreate(SettingsActivity.java:55)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at pansong291.xposed.quickenergy.util.Config.config2Json(Config.java:2149)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:2031)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1364)
	at pansong291.xposed.quickenergy.util.Config.languageSimplifiedChinese(Config.java:420)
	at pansong291.xposed.quickenergy.util.LanguageUtil.setLocale(LanguageUtil.java:12)
	at pansong291.xposed.quickenergy.ui.SettingsActivity.onCreate(SettingsActivity.java:55)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-26 22:45:17  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
2024-01-26 22:45:21  pansong291.xposed.quickenergy.util.FileUtils, statisticsFile.json文件不存在
2024-01-26 22:45:21  pansong291.xposed.quickenergy.util.Statistics, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JS

</code></pre></details>

**Comment by gitnoobbbb** [comment]
上个版本已解决此问题

**Comment by MJRweb** [comment]
谢谢，已解决，我的问题
解决方案，卸载模块重新安装（包括删除xqe文件夹）

**Comment by constanline** [comment]
不需要卸载模块，删除xqe文件夹重新配置即可。另外上个版本允许使用media文件夹存取配置。可以试试看。具体方式如下删了xqe文件夹后，在Download目录下创建useMedia文件夹，在Android/media文件夹下创建com.eg.android.AlipayGphone文件夹试试
