### ISSUE TITLE
遇到了支付宝无响应和forest.log没有写入权限的问题

### ISSUE THREAD

**Issue by tianyu8867** [constanline/XQuickEnergy#480]
### 程序版本 / 框架版本 / 模块版本

程序版本10.5.66.8000 框架版本 lsp1.8.6（6712） 模块版本v1.2.3-beta12

### 系统版本 / Android版本

MIUI14.0.5

### 详细描述问题发生的具体原因

一开始是更新支付宝和模块到最新版，遇到写入无权限的问题
![2297859ebee72d7bf45bcb8f0b8c573](https://github.com/constanline/XQuickEnergy/assets/30282022/9d1f94d5-f366-4ebc-a52a-a86307142e01)
![fedac5fe6cec5323a1c453f05b4d9e4](https://github.com/constanline/XQuickEnergy/assets/30282022/3a63edf1-8955-440b-9c9f-7f69311f4d10)
参考issue https://github.com/constanline/XQuickEnergy/issues/475 卸载模块重新安装（包括删除xqe文件夹）操作后出现支付宝无法打开
![703c27003a68438b5838bc202491e2e](https://github.com/constanline/XQuickEnergy/assets/30282022/bde5f7f9-1d02-4a65-9147-21c3e019330b)
如果在lsp中取消模块生效，可以打开支付宝

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.FileUtils, config.json文件不存在
2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:1529)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1364)
	at pansong291.xposed.quickenergy.util.Config.languageSimplifiedChinese(Config.java:420)
	at pansong291.xposed.quickenergy.util.LanguageUtil.setLocale(LanguageUtil.java:12)
	at pansong291.xposed.quickenergy.ui.MainActivity.onCreate(MainActivity.java:86)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3798)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Config, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at pansong291.xposed.quickenergy.util.Config.config2Json(Config.java:2149)
	at pansong291.xposed.quickenergy.util.Config.json2Config(Config.java:2031)
	at pansong291.xposed.quickenergy.util.Config.getConfig(Config.java:1364)
	at pansong291.xposed.quickenergy.util.Config.languageSimplifiedChinese(Config.java:420)
	at pansong291.xposed.quickenergy.util.LanguageUtil.setLocale(LanguageUtil.java:12)
	at pansong291.xposed.quickenergy.ui.MainActivity.onCreate(MainActivity.java:86)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3798)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.FileUtils, statisticsFile.json文件不存在
2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Statistics, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at pansong291.xposed.quickenergy.util.Statistics.json2Statistics(Statistics.java:857)
	at pansong291.xposed.quickenergy.util.Statistics.getStatistics(Statistics.java:751)
	at pansong291.xposed.quickenergy.util.Statistics.getText(Statistics.java:208)
	at pansong291.xposed.quickenergy.ui.MainActivity.onResume(MainActivity.java:114)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1565)
	at android.app.Activity.performResume(Activity.java:8668)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4960)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5003)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Statistics, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at pansong291.xposed.quickenergy.util.Statistics.statistics2Json(Statistics.java:1149)
	at pansong291.xposed.quickenergy.util.Statistics.json2Statistics(Statistics.java:1112)
	at pansong291.xposed.quickenergy.util.Statistics.getStatistics(Statistics.java:751)
	at pansong291.xposed.quickenergy.util.Statistics.getText(Statistics.java:208)
	at pansong291.xposed.quickenergy.ui.MainActivity.onResume(MainActivity.java:114)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1565)
	at android.app.Activity.performResume(Activity.java:8668)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4960)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5003)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

2024-01-30 11:42:41  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2024-01-30 11:42:45  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, get config fromapp
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-30 11:44:00  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.FileUtils, [null][config]读:true;写:true
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-30 11:47:34  pansong291.xposed.quickenergy.util.FileUtils, [app][statistics]读:true;写:true
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, get config fromapp
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, doubleCard:false
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:false
2024-01-30 11:55:26  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, get config fromnull
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.FileUtils, [null][config]读:true;写:true
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, limitCollect:true
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, limitCount:50
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, doubleCard:true
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, doubleCountLimit:6
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClick:true
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.Config, exchangeEnergyDoubleClickCount:6
2024-01-30 12:02:06  pansong291.xposed.quickenergy.util.FileUtils, [app][statistics]读:true;写:true

</code></pre></details>

**Comment by Zhangfanyu1222** [comment]
删了xqe文件夹后，在Download目录下创建useMedia文件夹，在Android/media文件夹下创建com.eg.android.AlipayGphone文件夹试试

**Comment by O-kai** [comment]
同样有这个问题，现在已经解决了。谢谢！

**Comment by GyAngel** [comment]
> 删了xqe文件夹后，在Download目录下创建useMedia文件夹，在Android/media文件夹下创建com.eg.android.AlipayGphone文件夹试试

按照这个方法，支付宝可以进入了，但是不收能量啥的。这是哪里有问题吗？

**Comment by Yxuan18** [comment]
> 这个方法，支付宝可以进入了，但是不收能量啥的。这

我这边再次打开以后，没有再次新建文 `xqe` 文件夹，然后相关的 log 文件也是 FILE_NOT_FOUND
澎湃OS，小米14P
