### ISSUE TITLE
勾选后支付宝无响应无法进入

### ISSUE THREAD

**Issue by GyAngel** [constanline/XQuickEnergy#488]
### 程序版本 / 框架版本 / 模块版本

程序版本 (10.5.66.8000)、框架版本 (例如：LSPosed 1.9.1) 、模块版本 (v1.2.3 bate12)

### 系统版本 / Android版本

系统版本：xiaomi hyperos 1.0.2.0，Android 14

### 详细描述问题发生的具体原因

在lsp里用芝麻粒勾选支付宝以后，支付宝进入无响应

### 提供模块问题 Log 或必要 Log

  at pansong291.xposed.quickenergy.util.FileUtils.append2File(FileUtils.java:399)
  at pansong291.xposed.quickenergy.util.FileUtils.append2RuntimeLogFile(FileUtils.java:375)
  at pansong291.xposed.quickenergy.util.Log.i(Log.java:12)
  at pansong291.xposed.quickenergy.AntForestToast.show(AntForestToast.java:46)
  at pansong291.xposed.quickenergy.util.FileUtils.append2File(FileUtils.java:400)
  at pansong291.xposed.quickenergy.util.FileUtils.append2RuntimeLogFile(FileUtils.java:375)
  at pansong291.xposed.quickenergy.util.Log.i(Log.java:12)
  at pansong291.xposed.quickenergy.AntForestToast.show(AntForestToast.java:46)
  at pansong291.xposed.quickenergy.util.FileUtils.append2File(FileUtils.java:400)
  at pansong291.xposed.quickenergy.util.FileUtils.append2RuntimeLogFile(FileUtils.java:375)

**Comment by Kaer321** [comment]
我也是这问题

**Comment by GyAngel** [comment]
> 我也是这问题

我是升级了 b12 和最新的支付宝才这样的。。。不知道怎么弄了。。。请问解决了吗

**Comment by yshb123** [comment]
我也是，没啥办法解决，用之前版本还不收好友能量

**Comment by Kaer321** [comment]
> > 我也是这问题
> 
> 我是升级了 b12 和最新的支付宝才这样的。。。不知道怎么弄了。。。请问解决了吗

解决了 参考https://github.com/constanline/XQuickEnergy/issues/480

**Comment by GyAngel** [comment]
> > > 我也是这问题
> > 
> > 我是升级了 b12 和最新的支付宝才这样的。。。不知道怎么弄了。。。请问解决了吗
> 
> 解决了 参考https://github.com/constanline/XQuickEnergy/issues/480

我看说删除 xqe。。。这个在哪。。。

**Comment by GyAngel** [comment]
> > > 我也是这问题
> > 
> > 我是升级了 b12 和最新的支付宝才这样的。。。不知道怎么弄了。。。请问解决了吗
> 
> 解决了 参考https://github.com/constanline/XQuickEnergy/issues/480

按照这个方法，支付宝可以进入了，但是不收能量啥的。这是哪里有问题吗？

**Comment by Kaer321** [comment]
可以收啊，你把支付宝还有插件都清除数据和缓存重新打开试试

**Comment by GyAngel** [comment]
> 可以收啊，你把支付宝还有插件都清除数据和缓存重新打开试试

清除了支付宝和芝麻粒的数据以后，在Download目录下创建一个useMedia文件夹，在Android/media文件夹下创建 com.eg.android.AlipayGphone文件
夹，然后运行两个软件对吧？
